# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-30 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datosCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion_envio', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mensaje', models.CharField(max_length=200)),
            ],
        ),
    ]
